import { z } from "zod";

export const OrderStatusEnum = z.enum([
  "pending",
  "preparing",
  "ready",
  "served",
  "cancelled",
  "done",
]);

export const PaymentStatusEnum = z.enum([
  "pending",
  "paid",
  "partially_paid",
  "refunded",
]);

export const OrderItemSchema = z.object({
  menuid: z.string().min(1, "Menu ID is required"),
  notes: z.string().optional(),
  quantity: z.number().min(1, "Quantity must be at least 1"),
});

export const OrderSchema = z.object({
  orderid: z.string().optional(), // auto-generated by backend
  tableid: z.string().min(1, "Table ID is required"),
  tableNumber: z.string().min(1, "Table number is required"),
  customerName: z.string().optional(),
  customerPhone: z.string().optional(),
  items: z.array(OrderItemSchema).min(1, "At least one item is required"),
  subtotal: z.number().nonnegative(),
  status: OrderStatusEnum.default("pending"),
});
